export const GET_CARDS_REQUEST = "GET_CARDS_REQUEST";
export const GET_CARDS_SUCCESS = "GET_CARDS_SUCCESS";
export const GET_CARDS_FAILLURE = "GET_CARDS_FAILLURE";

export const CHOOSE_CATEGORY = "CHOOSE_CATEGORY";

export const CHOOSE_PAGINATION = "CHOOSE_PAGINATION";
export const INCREMENT_PAGINATION = "INCREMENT_PAGINATION";
export const DECREMENT_PAGINATION = "DECREMENT_PAGINATION";
export const RESET_PAGINATION = "RESET_PAGINATION";

export const DELETE_CARD = "DELETE_CARD";

export const LIKE = "LIKE";
export const DISLIKE = "DISLIKE";
